/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsCategorySlugRouteImport } from './routes/products/$categorySlug'
import { Route as ProductsCategorySlugIndexRouteImport } from './routes/products/$categorySlug.index'
import { Route as ProductsCategorySlugSeriesSlugRouteImport } from './routes/products/$categorySlug.$seriesSlug'
import { Route as ProductsCategorySlugSeriesSlugIndexRouteImport } from './routes/products/$categorySlug.$seriesSlug.index'
import { Route as ProductsCategorySlugSeriesSlugProductSlugRouteImport } from './routes/products/$categorySlug.$seriesSlug.$productSlug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: '/products/$categorySlug',
  path: '/products/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategorySlugIndexRoute =
  ProductsCategorySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProductsCategorySlugRoute,
  } as any)
const ProductsCategorySlugSeriesSlugRoute =
  ProductsCategorySlugSeriesSlugRouteImport.update({
    id: '/$seriesSlug',
    path: '/$seriesSlug',
    getParentRoute: () => ProductsCategorySlugRoute,
  } as any)
const ProductsCategorySlugSeriesSlugIndexRoute =
  ProductsCategorySlugSeriesSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProductsCategorySlugSeriesSlugRoute,
  } as any)
const ProductsCategorySlugSeriesSlugProductSlugRoute =
  ProductsCategorySlugSeriesSlugProductSlugRouteImport.update({
    id: '/$productSlug',
    path: '/$productSlug',
    getParentRoute: () => ProductsCategorySlugSeriesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/$categorySlug': typeof ProductsCategorySlugRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categorySlug/$seriesSlug': typeof ProductsCategorySlugSeriesSlugRouteWithChildren
  '/products/$categorySlug/': typeof ProductsCategorySlugIndexRoute
  '/products/$categorySlug/$seriesSlug/$productSlug': typeof ProductsCategorySlugSeriesSlugProductSlugRoute
  '/products/$categorySlug/$seriesSlug/': typeof ProductsCategorySlugSeriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsIndexRoute
  '/products/$categorySlug': typeof ProductsCategorySlugIndexRoute
  '/products/$categorySlug/$seriesSlug/$productSlug': typeof ProductsCategorySlugSeriesSlugProductSlugRoute
  '/products/$categorySlug/$seriesSlug': typeof ProductsCategorySlugSeriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products/$categorySlug': typeof ProductsCategorySlugRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$categorySlug/$seriesSlug': typeof ProductsCategorySlugSeriesSlugRouteWithChildren
  '/products/$categorySlug/': typeof ProductsCategorySlugIndexRoute
  '/products/$categorySlug/$seriesSlug/$productSlug': typeof ProductsCategorySlugSeriesSlugProductSlugRoute
  '/products/$categorySlug/$seriesSlug/': typeof ProductsCategorySlugSeriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products/$categorySlug'
    | '/products/'
    | '/products/$categorySlug/$seriesSlug'
    | '/products/$categorySlug/'
    | '/products/$categorySlug/$seriesSlug/$productSlug'
    | '/products/$categorySlug/$seriesSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/products/$categorySlug'
    | '/products/$categorySlug/$seriesSlug/$productSlug'
    | '/products/$categorySlug/$seriesSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/products/$categorySlug'
    | '/products/'
    | '/products/$categorySlug/$seriesSlug'
    | '/products/$categorySlug/'
    | '/products/$categorySlug/$seriesSlug/$productSlug'
    | '/products/$categorySlug/$seriesSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$categorySlug': {
      id: '/products/$categorySlug'
      path: '/products/$categorySlug'
      fullPath: '/products/$categorySlug'
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$categorySlug/': {
      id: '/products/$categorySlug/'
      path: '/'
      fullPath: '/products/$categorySlug/'
      preLoaderRoute: typeof ProductsCategorySlugIndexRouteImport
      parentRoute: typeof ProductsCategorySlugRoute
    }
    '/products/$categorySlug/$seriesSlug': {
      id: '/products/$categorySlug/$seriesSlug'
      path: '/$seriesSlug'
      fullPath: '/products/$categorySlug/$seriesSlug'
      preLoaderRoute: typeof ProductsCategorySlugSeriesSlugRouteImport
      parentRoute: typeof ProductsCategorySlugRoute
    }
    '/products/$categorySlug/$seriesSlug/': {
      id: '/products/$categorySlug/$seriesSlug/'
      path: '/'
      fullPath: '/products/$categorySlug/$seriesSlug/'
      preLoaderRoute: typeof ProductsCategorySlugSeriesSlugIndexRouteImport
      parentRoute: typeof ProductsCategorySlugSeriesSlugRoute
    }
    '/products/$categorySlug/$seriesSlug/$productSlug': {
      id: '/products/$categorySlug/$seriesSlug/$productSlug'
      path: '/$productSlug'
      fullPath: '/products/$categorySlug/$seriesSlug/$productSlug'
      preLoaderRoute: typeof ProductsCategorySlugSeriesSlugProductSlugRouteImport
      parentRoute: typeof ProductsCategorySlugSeriesSlugRoute
    }
  }
}

interface ProductsCategorySlugSeriesSlugRouteChildren {
  ProductsCategorySlugSeriesSlugProductSlugRoute: typeof ProductsCategorySlugSeriesSlugProductSlugRoute
  ProductsCategorySlugSeriesSlugIndexRoute: typeof ProductsCategorySlugSeriesSlugIndexRoute
}

const ProductsCategorySlugSeriesSlugRouteChildren: ProductsCategorySlugSeriesSlugRouteChildren =
  {
    ProductsCategorySlugSeriesSlugProductSlugRoute:
      ProductsCategorySlugSeriesSlugProductSlugRoute,
    ProductsCategorySlugSeriesSlugIndexRoute:
      ProductsCategorySlugSeriesSlugIndexRoute,
  }

const ProductsCategorySlugSeriesSlugRouteWithChildren =
  ProductsCategorySlugSeriesSlugRoute._addFileChildren(
    ProductsCategorySlugSeriesSlugRouteChildren,
  )

interface ProductsCategorySlugRouteChildren {
  ProductsCategorySlugSeriesSlugRoute: typeof ProductsCategorySlugSeriesSlugRouteWithChildren
  ProductsCategorySlugIndexRoute: typeof ProductsCategorySlugIndexRoute
}

const ProductsCategorySlugRouteChildren: ProductsCategorySlugRouteChildren = {
  ProductsCategorySlugSeriesSlugRoute:
    ProductsCategorySlugSeriesSlugRouteWithChildren,
  ProductsCategorySlugIndexRoute: ProductsCategorySlugIndexRoute,
}

const ProductsCategorySlugRouteWithChildren =
  ProductsCategorySlugRoute._addFileChildren(ProductsCategorySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsCategorySlugRoute: ProductsCategorySlugRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
